### ISSUE TITLE
Ensure correct data value type for value rendering and total calculations in Pivot Engine

### ISSUE THREAD

**Issue by amcgee** [dhis2/analytics#297]
Ref #279 

![Screenshot 2020-02-12 16 43 31](https://user-images.githubusercontent.com/947888/74351047-dddf3180-4db6-11ea-8575-095e710ba247.png)

**Comment by amcgee** [comment]
keepalive

**Comment by varl** [comment]
Superseded by: https://jira.dhis2.org/browse/LIBS-5
