### ISSUE TITLE
Don't re-round values that are sent by the backend

### ISSUE THREAD

**Issue by amcgee** [dhis2/analytics#298]
From #279 

The way we currently do this may be a non-issue, since the backend now sends pre-rounded values, but we can't just render the server-provided value since it's a string and has extraneous 0s appended (i.e. `17.0` instead of `17`)

**Comment by amcgee** [comment]
keepalive

**Comment by varl** [comment]
Superseded by: https://jira.dhis2.org/browse/LIBS-4
